"""
Generate clinical reports from ML predictions using LLM.
Falls back to data-driven template when no LLM API is available.
"""
import os
import json
import logging
from typing import Dict

log = logging.getLogger(__name__)

LLM_PROVIDER = None
try:
    import anthropic
    if os.environ.get("ANTHROPIC_API_KEY"):
        LLM_PROVIDER = "anthropic"
except ImportError:
    pass

if not LLM_PROVIDER:
    try:
        import openai
        if os.environ.get("OPENAI_API_KEY"):
            LLM_PROVIDER = "openai"
    except ImportError:
        pass


class ClinicalReportGenerator:

    def __init__(self):
        self.provider = LLM_PROVIDER
        if self.provider == "anthropic":
            import anthropic as _a
            self.client = _a.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        elif self.provider == "openai":
            import openai as _o
            self.client = _o.OpenAI(api_key=os.environ["OPENAI_API_KEY"])
        else:
            self.client = None

    def generate(self, patient_data, prediction, confidence, shap_values, rag_context=""):
        has_shap = shap_values and any(abs(v) > 0.001 for v in shap_values.values())

        if self.provider and self.client:
            sorted_shap = sorted(shap_values.items(), key=lambda x: abs(x[1]), reverse=True)[:5]
            prompt = self._build_prompt(patient_data, prediction, confidence, sorted_shap, rag_context)
            try:
                if self.provider == "anthropic":
                    return self._call_anthropic(prompt)
                else:
                    return self._call_openai(prompt)
            except Exception as e:
                log.warning(f"LLM failed: {e}")

        ref = {"TSH": (0.4, 4.0, "mIU/L"), "T3": (0.8, 2.0, "ng/dL"),
               "T4": (60, 120, "nmol/L"), "T4U": (0.7, 1.2, ""), "FTI": (60, 120, "")}

        if has_shap:
            return self._shap_template(patient_data, prediction, confidence, shap_values, ref)
        return self.generate_from_data(patient_data, prediction, confidence, ref)

    def generate_from_data(self, patient_data, prediction, confidence, ref_ranges):
        tsh = patient_data.get("TSH", 0)
        t3 = patient_data.get("T3", 0)
        t4 = patient_data.get("T4", 0)
        age = patient_data.get("age", 0)

        findings = []
        for marker, (low, high, unit) in ref_ranges.items():
            val = patient_data.get(marker)
            if val is None:
                continue
            u = f" {unit}" if unit else ""
            if val > high:
                findings.append(f"**{marker}**: {val:.2f}{u} — **ELEVATED** (normal: {low}-{high})")
            elif val < low:
                findings.append(f"**{marker}**: {val:.2f}{u} — **LOW** (normal: {low}-{high})")
            else:
                findings.append(f"**{marker}**: {val:.2f}{u} — within normal range ({low}-{high})")

        interp = {
            "hypothyroid": f"elevated TSH ({tsh:.2f} mIU/L) with {'low' if t4 < 60 else 'borderline'} T4 ({t4:.1f} nmol/L), consistent with primary hypothyroidism",
            "hyperthyroid": f"suppressed TSH ({tsh:.2f} mIU/L) with {'elevated' if t3 > 2.0 else 'borderline'} T3 ({t3:.2f} ng/dL) and {'elevated' if t4 > 120 else 'borderline'} T4 ({t4:.1f} nmol/L), suggesting hyperthyroidism",
            "negative": f"thyroid markers within or near normal reference ranges (TSH: {tsh:.2f}, T3: {t3:.2f}, T4: {t4:.1f}), suggesting euthyroid state",
        }
        steps = {
            "hypothyroid": ["Repeat TSH and free T4 in 6-8 weeks to confirm", "Consider anti-TPO antibody testing", "If confirmed, initiate levothyroxine therapy"],
            "hyperthyroid": ["Order TSH receptor antibodies (TRAb)", "Consider radioactive iodine uptake scan", "Assess for tremor, weight loss, palpitations"],
            "negative": ["No immediate thyroid intervention required", "Routine screening per guidelines", "Re-evaluate if symptoms develop"],
        }

        report = f"""**CLINICAL REPORT — Thyroid Function Assessment**\n\n**1. CLINICAL SUMMARY**\n\nThe ML model predicts **{prediction.upper()}** with **{confidence:.1%}** confidence, based on {interp.get(prediction, 'pending correlation')}.\n\n**2. LAB VALUE ANALYSIS**\n\n"""
        for f in findings:
            report += f"- {f}\n"
        report += f"\n**3. CLINICAL CONTEXT**\n\n"
        if age:
            report += f"Patient is {int(age)} years old. "
        if patient_data.get("on_thyroxine"):
            report += "Currently on levothyroxine. "
        if patient_data.get("on_antithyroid"):
            report += "Currently on antithyroid medication. "
        if patient_data.get("pregnant"):
            report += "Patient is pregnant — trimester-specific TSH ranges apply. "
        report += f"\n\n**4. RECOMMENDED NEXT STEPS**\n\n"
        for s in steps.get(prediction, ["Correlate with clinical presentation"]):
            report += f"- {s}\n"
        report += "\n*Generated by ML clinical decision support. Not a substitute for clinical judgment.*"
        return report

    def _shap_template(self, patient_data, prediction, confidence, shap_values, ref_ranges):
        tsh, t3, t4 = patient_data.get("TSH", 0), patient_data.get("T3", 0), patient_data.get("T4", 0)
        top3 = sorted(shap_values.items(), key=lambda x: abs(x[1]), reverse=True)[:3]

        report = f"""**CLINICAL REPORT — Thyroid Function Assessment**\n\n**1. CLINICAL SUMMARY**\n\nThe ML model predicts **{prediction.upper()}** with **{confidence:.1%}** confidence.\nKey lab values: TSH={tsh:.2f} mIU/L, T3={t3:.2f} ng/dL, T4={t4:.1f} nmol/L.\n\n**2. KEY CONTRIBUTING FEATURES (SHAP)**\n\n"""
        for name, value in top3:
            direction = "pushes toward" if value > 0 else "pushes away from"
            strength = "strongly" if abs(value) > 1.0 else "moderately" if abs(value) > 0.3 else "slightly"
            actual = patient_data.get(name, "N/A")
            ref = ref_ranges.get(name)
            ref_str = f" (normal: {ref[0]}-{ref[1]} {ref[2]})" if ref else ""
            report += f"- **{name}** = {actual}{ref_str}: {strength} {direction} {prediction} (SHAP: {value:+.3f})\n"

        report += f"\n**3. MODEL EXPLANATION**\n\nPrediction driven by {top3[0][0]} ({top3[0][1]:+.3f}), {top3[1][0]} ({top3[1][1]:+.3f}), and {top3[2][0]} ({top3[2][1]:+.3f}).\n\n**4. RECOMMENDED NEXT STEPS**\n\n- Correlate ML findings with clinical presentation\n- Consider repeat thyroid tests in 6-8 weeks if subclinical\n- Refer to endocrinology if overt dysfunction confirmed\n\n*Generated by ML clinical decision support. Not a substitute for clinical judgment.*"
        return report

    def _build_prompt(self, patient_data, prediction, confidence, top_features, rag_context):
        fl = "\n".join(f"- {n}: contribution={v:+.3f}" for n, v in top_features)
        lit = f"\nMEDICAL LITERATURE:\n{rag_context}" if rag_context else ""
        return f"""Clinical decision support for thyroid diagnosis. Generate concise report.

PATIENT: {json.dumps(patient_data, indent=2)}
PREDICTION: {prediction} ({confidence:.1%})
SHAP FEATURES:\n{fl}
REFERENCE: TSH 0.4-4.0, T3 0.8-2.0, T4 60-120{lit}

Sections: 1.Summary 2.Key Findings 3.SHAP Explanation 4.Context 5.Next Steps. Under 250 words."""

    def _call_anthropic(self, prompt):
        r = self.client.messages.create(model="claude-sonnet-4-20250514", max_tokens=500,
                                        messages=[{"role": "user", "content": prompt}])
        return r.content[0].text

    def _call_openai(self, prompt):
        r = self.client.chat.completions.create(model="gpt-4o-mini", max_tokens=500,
                                                 messages=[{"role": "user", "content": prompt}])
        return r.choices[0].message.content
